service: serverless-aws

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: src/api/api.handler
    events:
      - http: GET /api
  todos:
    handler: src/api/todos.handler
    events:
      - http: GET /api/todos
