service: serverless-aws

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  stage: dev

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: yarn

package:
  individually: true

functions:
  api:
    handler: src/api.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

